### ISSUE TITLE
The build success notification has a confusing red background

### ISSUE THREAD

**Issue by jeanblanchard** [ggirou/yet-another-jenkins-notifier#15]
The build result (success or failure) notifications use the standard Jenkins icon, that happens to have a red background (it's the butler on a red circle, see the first screenshot in the readme). When I glance at the notification, my first impression is often that the build has failed, even when it has not.

Suggestions : either use the Jenkins icon without the red circle, or use a green (or blue) background to indicate a build success.

**Comment by ggirou** [comment]
Fixed in c67e2dc12db5dc0d75d39026ccbdccb0eb5c9e9a, have a look to the new icons in [img/logo-*.svg files](https://github.com/ggirou/yet-another-jenkins-notifier/tree/master/img) :)
It will be available in Chrome and Firefox soon.
