### ISSUE TITLE
Feature: Wildcard job checking

### ISSUE THREAD

**Issue by henricook** [ggirou/yet-another-jenkins-notifier#4]
Hi there,

On my very large jenkins installation (>1000 jobs) I have several 'views' e.g. http://myjenkins/views/donutFactory - this will show me a list of all the donutFactory jobs. It would be great if I could just point the plugin at this view and then whenever that team adds a new job it will be automatically picked up!

**Comment by ggirou** [comment]
I added the feature in #5, it will be available in Chrome Web Store soon.
Let me know if it performs well for you :)
